services:
  app:
    build: .
    ports:
      - '8000:8000'
    networks:
      - my_network
    volumes:
      - /mnt/network_share:/app/network_share
      - /home/mikhail/PycharmProjects/videoApp_files/complete_files:/app/complete_files
      - /home/mikhail/PycharmProjects/videoApp_files/upload_files:/app/upload_files
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      VIDEO_ARCHIVE_DB: ${VIDEO_ARCHIVE_DB}
      UPLOAD_DIRECTORY: ${UPLOAD_DIRECTORY}
      COMPLETE_FILES: ${COMPLETE_FILES}
      FOLDER_VIDEOS: ${FOLDER_VIDEOS}

  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my_network

  postgres:
    image: postgres:16-alpine
    container_name: postgres_for_videoApp
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
